export const fonts = [
    'BreeSerif',
    'Cucho Bold',
    'Cucho',
    'Fz Thư pháp Tiểu tự Fontzin',
    'Fz Thư pháp Đại tự Fontzin',
    'Gotham Medium',
    'Gotham Thin',
    'Gotham Ultra',
    'HP DNS Gibsons One Bold',
    'HP DNS Gibsons One Outline',
    'HP DNS Gibsons One Semi Bold',
    'HP DNS Gibsons One',
    'HP Monstice Base',
    'HP Monstice Emboss',
    'HP Monstice Engraved',
    'HP Monstice Inline',
    'iCiel Alina',
    'iCiel Altus Serif',
    'iCiel Altus',
    'iciel Cadena',
    'iCiel Crocante',
    'iCiel Finch bold',
    'iCiel Finch',
    'iCiel Kermel',
    'iCiel Pacifico',
    'iCiel Rukola',
    'iCiel TALUHLA',
    'iCielAmerigraf',
    'iCielBambola',
    'iCielCadena',
    'iCielParisSerif Bold',
    'iCielSoupofJustice',
    'KD Moon Light',
    'Mijas Ultra',
    'MTD 1613 Basilius',
    'MTD 21 Cent',
    'MTD Aaleyah Thick Stamp',
    'MTD Abbassy Script',
    'MTD Acryle Script',
    'MTD Addictype',
    'MTD Adventures Unlimited Sans',
    'MTD Adventures Unlimited Script Bold',
    'MTD Adventures Unlimited Script',
    'MTD Afecta',
    'MTD Alexandria',
    'MTD AlFresco',
    'MTD Amarone',
    'MTD Ampihan',
    'MTD Amstrong',
    'MTD Andrade Pro Script',
    'MTD Antro Vectra',
    'MTD Anydore',
    'MTD Ariestha',
    'MTD Arthington',
    'MTD Artisan',
    'MTD Attention Script',
    'MTD Auckland Script',
    'MTD Australian Script',
    'MTD Authemart',
    'MTD Authentica Rough',
    'MTD Auto Quick',
    'MTD Autogate Stamp',
    'MTD Ave Utan',
    'MTD Avelina',
    'MTD Babylonica ROB',
    'MTD Balerno Bold',
    'MTD Balerno Light',
    'MTD Balerno Regular',
    'MTD Barakah Regular',
    'MTD Bell Martellus',
    'MTD Bella Rose Alternates',
    'MTD Bella Rose Plain',
    'MTD Bella Rose',
    'MTD Benton',
    'MTD Berliana Monoline',
    'MTD Berrigela Anitta',
    'MTD Bertolessi',
    'MTD Bhaltazar',
    'MTD Bigilla Bold',
    'MTD Bigilla',
    'MTD Black and Shadow Font',
    'MTD Black Baron Gothic',
    'MTD Black Night',
    'MTD Blaze Glory',
    'MTD Blaze Glory Ornament',
    'MTD Blaze Glory Ornaments Drop',
    'MTD Blue Island Std',
    'MTD Brand Pro Inline',
    'MTD Brand Pro Light',
    'MTD Brand Pro Shade',
    'MTD Brand Pro',
    'MTD Brignola PUA Script',
    'MTD Briliants Typeface',
    'MTD Broadway Script Rough',
    'MTD Broadway Script',
    'MTD Brunette',
    'MTD Bubble',
    'MTD Buffied',
    'MTD Bunga SVG',
    'MTD Bunga',
    'MTD Caerphilly Regular',
    'MTD Candyland',
    'MTD Capellina Script',
    'MTD Carrington',
    'MTD Casanova Script EF Pro',
    'MTD Chalmers',
    'MTD Charlize One',
    'MTD Cheese Sauce',
    'MTD Chuck Noon Script',
    'MTD Cindo Kato',
    'MTD City Stencil',
    'MTD Clarkson Script Regular',
    'MTD Coffee Break Script 2',
    'MTD CS Delirian Script',
    'MTD CS Solange',
    'MTD Danielle Harris Caps',
    'MTD Dartangnon ITC',
    'MTD Daytonia',
    'MTD Doppelganger Display',
    'MTD Douglass Pen',
    'MTD Ecstasy TTW',
    'MTD Elipses Alt',
    'MTD Elipses Bold Alt',
    'MTD Elipses Bold',
    'MTD Elipses Caps',
    'MTD Elipses Italic Alt',
    'MTD Elipses Italic',
    'MTD Elipses',
    'MTD Elodie',
    'MTD Esther',
    'MTD Explorers',
    'MTD Fabulous Script',
    'MTD Familia Script',
    'MTD Fancy Melody',
    'MTD Fashion Vogue',
    'MTD Feather',
    'MTD Feliz En Vista Alternative',
    'MTD Feliz en Vista',
    'MTD Fiftyes',
    'MTD Fleurie',
    'MTD Francesca',
    'MTD Fun Play Day',
    'MTD Gambit Nouveau SG OT Std',
    'MTD Genia',
    'MTD Geraldyne',
    'MTD Gilroy Light Italic',
    'MTD Gilroy Light',
    'MTD Gilroy Medium Italic',
    'MTD Gilroy Medium',
    'MTD Gilroy Regular Italic',
    'MTD Gilroy Regular',
    'MTD Gilroy UltraLight Italic',
    'MTD Gilroy UltraLight',
    'MTD Girasol Shine',
    'MTD Girasol',
    'MTD Girly Things Regular',
    'MTD GoatskinBrush PersonalUse',
    'MTD Gogoia Deco',
    'MTD Good Day',
    'MTD Goodwater Brush',
    'MTD Goodwater Print Brush',
    'MTD Goodwater Print Sans 1',
    'MTD Goodwater Print Script 1',
    'MTD Goodwater Sans 2',
    'MTD Goodwater Script 1',
    'MTD Gorni',
    'MTD Grange',
    'MTD Great Vibes',
    'MTD Great Victorian Swashed',
    'MTD Greatlove',
    'MTD Greature',
    'MTD Habibe',
    'MTD Hangbird',
    'MTD Hard Stones Pro Rough',
    'MTD Hard Stones Pro Strip',
    'MTD Hard Stones Pro',
    'MTD Harukaze Slant',
    'MTD Harukaze Solid',
    'MTD Harukaze',
    'MTD Hayne Script Clean',
    'MTD Hello Paris Serif',
    'MTD Hey August',
    'MTD High Way',
    'MTD Hillstown Aged',
    'MTD Hillstown Clean',
    'MTD Himalaya Sans Serif',
    'MTD Himalaya',
    'MTD Hipster Script',
    'MTD Houstoner Script',
    'MTD Hu Kou',
    'MTD Hummingbird',
    'MTD Hummington',
    'MTD Jailetter',
    'MTD JRS',
    'MTD JV Signature Regular',
    'MTD Karolin',
    'MTD Katherine Script',
    'MTD Katheryna',
    'MTD Kawoszeh',
    'MTD King Edward Basic Inline Italic',
    'MTD King Edward Basic Inline',
    'MTD King Edward Basic Italic',
    'MTD King Edward Basic Shadow',
    'MTD King Edward Basic',
    'MTD King Edward Shadow',
    'MTD King Edward',
    'MTD Kiramba',
    'MTD Kosova',
    'MTD Lastone',
    'MTD Lazy Ride Script',
    'MTD LeJardin Floral',
    'MTD Letra Pro Headline',
    'MTD Levitee',
    'MTD Love',
    'MTD Loveletter No.9',
    'MTD Loveya Script',
    'MTD Madame Cosmetics',
    'MTD Magnies',
    'MTD Maryatha',
    'MTD Matsury',
    'MTD Mavera',
    'MTD Megrim',
    'MTD Middle Saxony Text',
    'MTD Midnight Tales',
    'MTD Milkstore 01 Script Textured',
    'MTD Milkstore 06 Textured',
    'MTD Mind Blowing Light',
    'MTD MitreSquare',
    'MTD MK Broken Types',
    'MTD Monopola Script',
    'MTD MusashiBB',
    'MTD Nettizen Script Dancing',
    'MTD New Year s Story',
    'MTD Oceania',
    'MTD Old Finlander',
    'MTD One Starry Night',
    'MTD Oops',
    'MTD Orangimelo',
    'MTD Othelie Line',
    'MTD Othelie',
    'MTD Owah Tagu Siam NF',
    'MTD P22 Ruthie',
    'MTD Palomino Sans One',
    'MTD Palomino Sans Two',
    'MTD Palomino Script',
    'MTD Parnas',
    'MTD PF DaVinci Script Pro Inked',
    'MTD PF DaVinci Script Pro',
    'MTD PN Macabre Millionaire',
    'MTD Portrait Script Bounce',
    'MTD Prida 01 Black',
    'MTD Prida 01 Bold',
    'MTD Prida 01 Light',
    'MTD Prida 01',
    'MTD Prida 02 Calt',
    'MTD QuangNinh Thuphap 1',
    'MTD QuangNinh Thuphap 2',
    'MTD Quaver',
    'MTD Queen Victoria Inine Swash',
    'MTD Queen Victoria Inline',
    'MTD Queen Victoria Outline',
    'MTD Queen Victoria Shadow',
    'MTD Queen Victoria Swash',
    'MTD Queen Victoria Vintage',
    'MTD Queen Victoria',
    'MTD Quimbly Bold',
    'MTD Quimbly Light',
    'MTD Quimbly',
    'MTD Ramblin Paint',
    'MTD Ranthing',
    'MTD Red Bright Swash',
    'MTD Red Bright',
    'MTD Renaissance Garden Italic',
    'MTD Retrology Block',
    'MTD Rockyeah Brush',
    'MTD Romance Fatal Serif Pro',
    'MTD Rose Petals Two',
    'MTD Rosemary Signature',
    'MTD Rossegenia',
    'MTD Roughish',
    'MTD Royal Touch',
    'MTD Sailing Heart Solid',
    'MTD Sailing Heart',
    'MTD Santiago',
    'MTD Santos Dumont',
    'MTD Scripture',
    'MTD Second Lyrics',
    'MTD Selva',
    'MTD Serenity Script',
    'MTD Shalima',
    'MTD Shapely',
    'MTD ShimesOne',
    'MTD Shodo Gothic',
    'MTD Shopping Script',
    'MTD Silver Crown',
    'MTD Simpletune',
    'MTD Sirunian',
    'MTD Skylar',
    'MTD Snow For Santa',
    'MTD Sofye',
    'MTD SouthPacific',
    'MTD Spagheti Script',
    'MTD Spooksville',
    'MTD Spring Chicken',
    'MTD SpringVibes Floral Light',
    'MTD SpringVibes Floral',
    'MTD SpringVibes',
    'MTD St Friska',
    'MTD Stanley Stamp',
    'MTD Stanley',
    'MTD Stanwood',
    'MTD Starcity Script',
    'MTD Stash Vintage Light',
    'MTD Stash Vintage',
    'MTD Streetwear',
    'MTD Summer Show',
    'MTD Thank You So Much',
    'MTD The Beauty Blink',
    'MTD The Beautyline',
    'MTD The Duality',
    'MTD The Hotelio',
    'MTD The Moon Falls',
    'MTD Thirsk',
    'MTD Tita Script Alt',
    'MTD Traditian',
    'MTD Troyline Script',
    'MTD Twas The Night Before Christmas',
    'MTD Ultimus',
    'MTD Unicorn Calligraphy',
    'MTD UT Sugar Cane',
    'MTD Valky Bold',
    'MTD Valky Light',
    'MTD Valky Regular',
    'MTD Valky Semibold',
    'MTD Verona Lotte',
    'MTD Volloa',
    'MTD Voyage Bold',
    'MTD Voyage Regular',
    'MTD VVD Golden Horn Lined',
    'MTD VVD Golden Horn Pressed',
    'MTD VVD Golden Horn Roughen',
    'MTD VVD Golden Horn Shadow',
    'MTD VVD Golden Horn',
    'MTD Wanita',
    'MTD WetSpring',
    'MTD Whittier',
    'MTD William Letter',
    'MTD Woolen',
    'MTD Xuong Rong 01',
    'MTD Yerington',
    'MTD Yessy',
    'MTD Yolanda Princess',
    'MTD Youther Script',
    'MTD Yozakura JP Light',
    'MTD Yozakura JP',
    'MyriadPro Regular',
    'Nabila',
    'OrtisanSignature',
    'OS Shiipt',
    'Pony',
    'scripti',
    'SDC Waliglona',
    'SDC Betalisa',
    'SDC Evitrian',
    'SDC House',
    'SDC Jhode',
    'SDC Sign Rathi',
    'SDC The Handwritten Watermark',
    'SDC Aaript',
    'SDC Abrace',
    'SDC Agolar',
    'SDC Agolic',
    'SDC Aguack',
    'SDC Agular',
    'SDC Aguold',
    'SDC Aleght',
    'SDC Alelar (2)',
    'SDC Alelic (3)',
    'SDC Alelic',
    'SDC Aleold (2)',
    'SDC Aleold.221207 1051',
    'SDC Aleold',
    'SDC Allipt',
    'SDC Allist',
    'SDC Ameats',
    'SDC Ameype',
    'SDC Ameyst',
    'SDC Amsdam',
    'SDC Amslar',
    'SDC Anasia',
    'SDC Angely',
    'SDC Angife',
    'SDC Anthem',
    'SDC Apoius',
    'SDC Arc897',
    'SDC ARCpSDC',
    'SDC Arctes',
    'SDC Arslon',
    'SDC Artuty',
    'SDC Aslrry',
    'SDC Astout',
    'SDC Athene',
    'SDC Audrey',
    'SDC Avaipt',
    'SDC Avence',
    'SDC Babtar',
    'SDC Balace',
    'SDC Baleer',
    'SDC Balipt',
    'SDC Bango',
    'SDC Banins',
    'SDC Baript',
    'SDC Barrif',
    'SDC BaSDCek',
    'SDC Batate',
    'SDC Beaans',
    'SDC Beaipt',
    'SDC Beaood',
    'SDC Beaord',
    'SDC Beatok',
    'SDC Bebace',
    'SDC BeCool',
    'SDC Belers',
    'SDC Bellico',
    'SDC Belved',
    'SDC Besach',
    'SDC Biging',
    'SDC Bilold',
    'SDC Bisipt',
    'SDC Bjola',
    'SDC BLAAWK',
    'SDC Blahid',
    'SDC Blaill',
    'SDC Blaond',
    'SDC Blauff',
    'SDC Bloipt',
    'SDC Bloush',
    'SDC Blyofs',
    'SDC Bonage',
    'SDC Bonour',
    'SDC Bouher',
    'SDC Bouipt',
    'SDC Bradow',
    'SDC Braga',
    'SDC Briold',
    'SDC Brotch',
    'SDC Brript',
    'SDC Bruipt',
    'SDC Brutte',
    'SDC Bubont',
    'SDC Buiton',
    'SDC Bulary',
    'SDC Calama',
    'SDC Calipt',
    'SDC Canipt',
    'SDC Canpee',
    'SDC Capipt',
    'SDC Carerg',
    'SDC Carola',
    'SDC Carsta',
    'SDC Carwer',
    'SDC Caving',
    'SDC Chalest',
    'SDC Cherga',
    'SDC Chioup',
    'SDC Chirie',
    'SDC Choipt',
    'SDC Cinake',
    'SDC Cintra',
    'SDC Clania',
    'SDC Cleine',
    'SDC Cloice',
    'SDC Coco FY',
    'SDC Codrux',
    'SDC Condot',
    'SDC Conreu',
    'SDC Consent',
    'SDC Cooilk',
    'SDC Corcan',
    'SDC Corded',
    'SDC Corish',
    'SDC Corlar',
    'SDC Cotuse',
    'SDC Cupake',
    'SDC Cyrano',
    'SDC DaiLau',
    'SDC Darton',
    'SDC Dayand',
    'SDC Days',
    'SDC Deaane',
    'SDC Deaipt',
    'SDC Delsto',
    'SDC Dentra',
    'SDC Desipt',
    'SDC Desire',
    'SDC Desyrel',
    'SDC Detans',
    'SDC DHFush',
    'SDC DHrush',
    'SDC Diablo',
    'SDC Diaond',
    'SDC Digalis',
    'SDC DKCard',
    'SDC Domque',
    'SDC Doodly',
    'SDC Dopipt',
    'SDC Dowver',
    'SDC Duming',
    'SDC Egript',
    'SDC Elley',
    'SDC Endord',
    'SDC Endrow',
    'SDC Engine',
    'SDC Erimig',
    'SDC EsmPro',
    'SDC Eupnic',
    'SDC Eveeen',
    'SDC Eveght',
    'SDC Fadlla',
    'SDC Fashion',
    'SDC Feling',
    'SDC Ferlar',
    'SDC FjaOne',
    'SDC Flaipt',
    'SDC Fonine',
    'SDC Forlly',
    'SDC Foular',
    'SDC Fouold',
    'SDC Freipt',
    'SDC Freude',
    'SDC Freyle',
    'SDC Galern',
    'SDC Ganree',
    'SDC Gariny',
    'SDC GenPro',
    'SDC Geoipt',
    'SDC Giaza',
    'SDC Ginger',
    'SDC Glojah',
    'SDC Golaps',
    'SDC Golipt',
    'SDC Golype',
    'SDC Graamo',
    'SDC Gracia',
    'SDC Grahez',
    'SDC Graitel',
    'SDC Gralay 2',
    'SDC Gralay',
    'SDC Gralic',
    'SDC Graman',
    'SDC Groded',
    'SDC Guella',
    'SDC Gumley',
    'SDC Haming',
    'SDC Handlar',
    'SDC Hanold',
    'SDC HanPro',
    'SDC HanTwo',
    'SDC Hapipt',
    'SDC Harony',
    'SDC Harpt',
    'SDC Havart',
    'SDC Heaeen',
    'SDC Heaner',
    'SDC Heanly',
    'SDC Heaoth',
    'SDC Heaoul',
    'SDC Heimer',
    'SDC Helcky',
    'SDC Helets',
    'SDC Helga',
    'SDC Heline (2)',
    'SDC Heline',
    'SDC HelInk',
    'SDC Helker',
    'SDC Herine',
    'SDC HerPro',
    'SDC Hirake',
    'SDC Hogfish',
    'SDC Holday',
    'SDC Holkes',
    'SDC HolPro',
    'SDC Hopsed',
    'SDC Hotsta',
    'SDC Houure',
    'SDC Hughs',
    'SDC Ilyas',
    'SDC Indie',
    'SDC Intade',
    'SDC Intase',
    'SDC Iolthe',
    'SDC Janten',
    'SDC Jantus',
    'SDC Jeaous',
    'SDC Jonipt',
    'SDC Journey',
    'SDC Jusday',
    'SDC Jusing',
    'SDC Justgue',
    'SDC Karlita',
    'SDC Karsha',
    'SDC Kasush',
    'SDC Kelso',
    'SDC Kintom',
    'SDC Kitten',
    'SDC Koma',
    'SDC Konras',
    'SDC KorpSDC',
    'SDC LaPoma',
    'SDC Larded',
    'SDC Lasise',
    'SDC LeBNew',
    'SDC Lemday',
    'SDC LeMure',
    'SDC LeOsler',
    'SDC Lifans',
    'SDC Lifipt',
    'SDC Lifsic',
    'SDC Lolack',
    'SDC Lonide',
    'SDC Lostar',
    'SDC Lovion',
    'SDC Lovure',
    'SDC Ludous',
    'SDC Lusipt',
    'SDC Mablla',
    'SDC Madipt',
    'SDC Magent',
    'SDC Manark',
    'SDC Manrry',
    'SDC Maplla',
    'SDC Marino',
    'SDC Marpro (2)',
    'SDC MarPro',
    'SDC Marres',
    'SDC Marujo',
    'SDC Mauipt',
    'SDC Megnte',
    'SDC Merria',
    'SDC Merular',
    'SDC Micine',
    'SDC Milams',
    'SDC Modety',
    'SDC Momnto',
    'SDC Moname',
    'SDC Moorth',
    'SDC Mosshi',
    'SDC Motica',
    'SDC Mukdua',
    'SDC Naiold',
    'SDC Nauica',
    'SDC Neuace',
    'SDC NewM54',
    'SDC Nexack',
    'SDC Nexded',
    'SDC Nexdow',
    'SDC Nexipt',
    'SDC Nicipt',
    'SDC Nigent',
    'SDC Norold',
    'SDC Norular',
    'SDC Notera',
    'SDC Noting',
    'SDC Notold',
    'SDC Novlia',
    'SDC Nubya',
    'SDC Nuit',
    'SDC OneDay',
    'SDC Orishu',
    'SDC PalaLC',
    'SDC Palint',
    'SDC Palipt',
    'SDC Palton',
    'SDC Parise',
    'SDC ParPro',
    'SDC Pasnak',
    'SDC Passion',
    'SDC Patipt',
    'SDC Pentic',
    'SDC Peqack',
    'SDC Peqlar',
    'SDC Pleent',
    'SDC Posine',
    'SDC Progs',
    'SDC Pyeine',
    'SDC Qalrif',
    'SDC Qualar',
    'SDC Quarzo',
    'SDC Radder',
    'SDC Rawone',
    'SDC Redwns',
    'SDC RekaCF',
    'SDC Rekipt',
    'SDC Ret000',
    'SDC Ridlar',
    'SDC Ridold',
    'SDC Rinena',
    'SDC Rio016',
    'SDC RisPro',
    'SDC Roaage',
    'SDC Roaush',
    'SDC Rocess',
    'SDC Rohtwo',
    'SDC Rolury',
    'SDC Romcho',
    'SDC Rosipt',
    'SDC Rosnda',
    'SDC Rosore',
    'SDC Ruca',
    'SDC Rusick',
    'SDC Rusour',
    'SDC Sabper',
    'SDC Safipt',
    'SDC Sage 2',
    'SDC Sage',
    'SDC Saiica',
    'SDC Salans',
    'SDC Salina',
    'SDC Salipt',
    'SDC Sambay',
    'SDC Santer',
    'SDC Santis',
    'SDC Sarifa',
    'SDC Saugar',
    'SDC Sayeez',
    'SDC SecPro',
    'SDC Seiton',
    'SDC Serhin',
    'SDC Serium',
    'SDC Sevana',
    'SDC Shapen',
    'SDC Shiaru',
    'SDC Shoans',
    'SDC Sholab',
    'SDC Sigipt',
    'SDC Silver',
    'SDC Skill',
    'SDC Slaush',
    'SDC Sloack 2',
    'SDC Sloack',
    'SDC Smirk',
    'SDC Snelipt',
    'SDC Sneold',
    'SDC SpaAge',
    'SDC Spldor',
    'SDC Stadly',
    'SDC Steady',
    'SDC Stella',
    'SDC Steows',
    'SDC Stiaff',
    'SDC Stiing',
    'SDC Stiray',
    'SDC Stiund',
    'SDC Stoans',
    'SDC Storif',
    'SDC Strdas',
    'SDC Strove',
    'SDC Stuush',
    'SDC Suagie',
    'SDC Sunday',
    'SDC Sunine',
    'SDC Sunora',
    'SDC Sunower',
    'SDC Supgic',
    'SDC Swaton',
    'SDC Swetie',
    'SDC Swiium',
    'SDC Swilar',
    'SDC Takres',
    'SDC Tamdo',
    'SDC Tanans',
    'SDC Tango',
    'SDC Tanine',
    'SDC Tanipt',
    'SDC Teaers',
    'SDC Theans',
    'SDC Theers',
    'SDC Theipt',
    'SDC Thelar',
    'SDC Theold',
    'SDC Theory',
    'SDC Theret',
    'SDC Tinipt',
    'SDC Tioans',
    'SDC Tipper',
    'SDC TokgPx',
    'SDC Topret',
    'SDC Toyans',
    'SDC TraDark',
    'SDC Trench',
    'SDC TruPro',
    'SDC Twiipt',
    'SDC UncBen',
    'SDC UnTift',
    'SDC UTTess',
    'SDC UTTlar',
    'SDC Vala',
    'SDC Vamres',
    'SDC Vanlla',
    'SDC VanPro',
    'SDC Velies',
    'SDC Veneer',
    'SDC Verine',
    'SDC Verrry',
    'SDC Vicria',
    'SDC Walows',
    'SDC Walton',
    'SDC Watlar.221213 1707',
    'SDC Watlar',
    'SDC Watold',
    'SDC Wedday',
    'SDC Welont',
    'SDC Wendi',
    'SDC WeYuth',
    'SDC Wooker',
    'SDC Wrisno',
    'SDC Wrount',
    'SDC Wylgen',
    'SDC XXIipt',
    'SDC Yamasi',
    'SDC Yipes',
    'SDC Youove',
    'SDC Zaiipt',
    'SDC Zatyan',
    'SDC Zicets',
    'SVN Aaron Script',
    'SVN Abril Fatface',
    'SVN Adeline',
    'SVN Agoka Italic',
    'SVN Agoka Regular',
    'SVN Aguda Black',
    'SVN Aguda Bold',
    'SVN Aguda Light',
    'SVN Aguda Regular',
    'SVN Alek Bold',
    'SVN Alek Regular',
    'SVN Aleo Bold Italic',
    'SVN Aleo Bold',
    'SVN Aleo Italic',
    'SVN Aleo Light Italic',
    'SVN Aleo Light',
    'SVN Aleo Regular',
    'SVN Allea Script',
    'SVN Allogist',
    'SVN Amethyst Dingbats',
    'SVN Amethyst TrueType',
    'SVN Amethyst',
    'SVN Ameyallinda Signature',
    'SVN Amsdam',
    'SVN Amstirdam',
    'SVN Anastasia',
    'SVN Angellife',

    'SVN Angely',
    'SVN Anthem',
    'SVN Apollonius',
    'SVN Archaic 1897',
    'SVN Archattes',
    'SVN ARCO Typography',
    'SVN Arsilon',
    'SVN Artful Beauty',
    'SVN Aslang Barry',
    'SVN Astronout',
    'SVN Athene',
    'SVN Audrey',
    'SVN Avaline Script',
    'SVN Avengeance',
    'SVN Baby Youre A Star',
    'SVN Bahud Aroyek',
    'SVN Bali Script',
    'SVN Balladeer Light',
    'SVN Ballarea Typeface',
    'SVN Banana Chip Muffins',
    'SVN Bango',
    'SVN Barnyard Script',
    'SVN Barnyard Serif',
    'SVN Batman Forever Alternate',
    'SVN Be Cool',
    'SVN Beachwood Sans',
    'SVN Beachwood Script',
    'SVN Beauford',
    'SVN Beauty Atok Script',
    'SVN Bebop Slab Face',
    'SVN Bellwethers',
    'SVN Beloved',
    'SVN Bestagrach',
    'SVN Betalisa',
    'SVN Big Noodle Titling',
    'SVN Billy Bold',
    'SVN Bistro Script',
    'SVN Black Diamond',
    'SVN Black Orchid',
    'SVN Black Stuff Bold',
    'SVN BLACKHAWK',
    'SVN Bladekill',
    'SVN Blenda Script',
    'SVN Blog Script',
    'SVN Blow Brush',
    'SVN Blywoofs',
    'SVN Bonjour',
    'SVN BonVoyage Regular',
    'SVN Bougher',
    'SVN Boutique Script',
    'SVN Braga',
    'SVN Brandon Printed Shadow',
    'SVN Briko Bold',
    'SVN Brownhill Script',
    'SVN Brunette',
    'SVN Bruselo Script',
    'SVN Bublont',
    'SVN Buinton',
    'SVN Bulgary',
    'SVN Calama',
    'SVN Callpedia Script',
    'SVN Candy Script',
    'SVN Canopee',
    'SVN Caprica Script',
    'SVN Carista',
    'SVN Carlosberg',
    'SVN Carola',
    'SVN Carrotflower',
    'SVN Cavorting',
    'SVN Chalkboard The Best',
    'SVN Cheeky Rabbit',
    'SVN Cheeseburga',
    'SVN Chicken Noodle Soup',
    'SVN Childish Reverie',
    'SVN Chopin Script',
    'SVN Cinnamoncake',
    'SVN Cintra',
    'SVN Claytonia',
    'SVN Clementine',
    'SVN Clouds Caprice',
    'SVN Coco FY',
    "SVN Coder's Crux",
    'SVN Coder s Crux',
    'SVN Conqueror Didot',
    'SVN Consent',
    'SVN Constreu',
    'SVN Cookies And Milk',
    'SVN Corki Regular',
    'SVN Corki Rounded',
    'SVN Corki Tuscan Rounded',
    'SVN Corki Tuscan',
    'SVN Cornish',
    'SVN Cottage & Farmhouse',
    'SVN Cupcake',
    'SVN Cyrano',
    'SVN Daisy Lau',
    'SVN Darleston',
    'SVN Dayland',
    'SVN Days',
    'SVN Deadhead Script',
    'SVN Dear Jane',
    'SVN Delabasto',
    'SVN Dentra',
    'SVN Desire',
    'SVN Dessert Menu Script',
    'SVN Desyrel',
    'SVN Determination Sans',
    'SVN DHF Dexsar Brush',
    "SVN DHF Harry's Brush",
    'SVN Diablo',
    'SVN Diamond',
    'SVN Diamonda',
    'SVN Digitalis',
    'SVN DK Clochard',
    'SVN Dominique',
    'SVN Doodly',
    'SVN Dope Script',
    'SVN Down River',
    'SVN Dumpling',
    'SVN Egregio Script',
    'SVN Elley',
    'SVN Endless Sorrow',
    'SVN Engine',
    'SVN Erika Ormig',
    'SVN Esmeralda Pro',
    'SVN Euphorigenic',
    'SVN Evergreen',
    'SVN Every Movie Every Night',
    'SVN Fadilla',
    'SVN Fashion',
    'SVN Felix Titling',
    'SVN Fergana Regular',
    'SVN Fjalla One',
    'SVN Flamingo Script',
    'SVN Fontaine',
    'SVN Fords Folly',
    'SVN Fourth Bold',
    'SVN Fourth Extras',
    'SVN Fourth Regular',
    'SVN Freestyle',
    'SVN Fresh Script',
    'SVN Freude',
    'SVN Friends Forever',
    'SVN Gallery Modern',
    'SVN Gang of Three',
    'SVN Garleriny',
    'SVN Genica Pro',
    'SVN Giaza',
    'SVN Ginger',
    'SVN Gloria Hallelujah',
    'SVN Golden Youth Caps',
    'SVN Goldeye Type',
    'SVN Gracia',
    'SVN Grahamo',
    'SVN GrandSlang Italic',
    'SVN GrandSlang Roman',
    'SVN Graphitel',
    'SVN Gratelos Display 2',
    'SVN Gratelos Display',
    'SVN Gravhez',
    'SVN Grocery Rounded',
    'SVN Guerrilla',
    'SVN Gumley',
    'SVN Hamstring',
    'SVN Hand Gothic Bold',
    'SVN Hand Gothic Regular',
    'SVN Hand Of Sean Pro',
    'SVN Handelson Two',
    'SVN Haptic Script',
    'SVN Harman Script',
    'SVN Harmony',
    'SVN Have Heart 2',
    'SVN Have Heart',
    'SVN HC 1785 GLC Baskerville',
    'SVN HC Aerojones NF',
    'SVN HC Alterner',
    'SVN HC Anas Rusty Typewriter',
    'SVN HC Anchor Jack',
    'SVN HC Appareo Black Italic',
    'SVN HC Appareo Black',
    'SVN HC Bauhaus 93',
    'SVN HC Belinda',
    'SVN HC Bernard MT Cond',
    'SVN HC Bourbon Grotesque',
    'SVN HC Braga Huis',
    'SVN HC Broadway Cond',
    'SVN HC Built Titling',
    'SVN HC Calvous',
    'SVN HC Carlson',
    'SVN HC Carosello',
    'SVN HC Colombo Sans',
    'SVN HC Cubano Sharp',
    'SVN HC Cubano',
    'SVN HC Culture',
    'SVN HC Cyrene',
    'SVN HC Deftone Stylus',
    'SVN HC East Market',
    'SVN HC Ekim Mezunu',
    'SVN HC Elixir Circus',
    'SVN HC Elixir Sans',
    'SVN HC Explorer Condensed',
    'SVN HC Gibsons One',
    'SVN HC Gibsons Two',
    'SVN HC Gneisenauette',
    'SVN HC Gorod',
    'SVN HC Green Grove',
    'SVN HC Grindstone Display',
    'SVN HC Haydon Brush',
    'SVN HC Impossibilium',
    'SVN HC Jungle Adventurer',
    'SVN HC Just Old Fashion',
    'SVN HC Kodiak',
    'SVN HC Lexington',
    'SVN HC Marvin Visions',
    'SVN HC Matura Script Capitals',
    'SVN HC Newyork Clean',
    'SVN HC Oilvare Base',
    'SVN HC Old Newspaper Types',
    'SVN HC Oldstyle Italic',
    'SVN HC Organ Grinder',
    'SVN HC Oronteus Finaeus',
    'SVN HC Pacifico',
    'SVN HC Quotes Caps',
    'SVN HC Quotes Script',
    'SVN HC Radiant Bold Cond',
    'SVN HC Read One',
    'SVN HC Rostrum',
    'SVN HC Santoro Script',
    'SVN HC Spot',
    'SVN HC Spy Royal',
    'SVN HC Stay Kool',
    'SVN HC Steak And Cheese Condensed',
    'SVN HC Steak And Cheese Pen',
    'SVN HC Steak And Cheese Slab',
    'SVN HC Strenuous',
    'SVN HC The Pretender',
    'SVN HC Transformacio',
    'SVN HC Velcro',
    'SVN HC Venhille Quaver',
    'SVN HC Yellowtail',
    'SVN HC Yeoman Gothic',
    'SVN Headliner No 45',
    'SVN Heart And Soul Smooth',
    'SVN Heart And Soul',
    'SVN Heathergreen',
    'SVN Heavenly',
    'SVN Heimer',
    'SVN Helga',
    'SVN Hello Headline',
    'SVN Hello Lucky Ink',
    'SVN Hello Lucky',
    'SVN Hello Sunshine Marker',
    'SVN Hello Sunshine',
    'SVN Hello Sweets',
    'SVN Heritage',
    'SVN Heroe Pro Inline',
    'SVN Heroe Pro Monoline',
    'SVN Heroe Pro',
    'SVN Hiro Misake',
    'SVN Hogfish',
    'SVN Holiday',
    'SVN Hollie Script Pro',
    'SVN Hollycakes',
    'SVN Hottroof Semhesta',
    'SVN Housttely Signature',
    'SVN Hughs',
    'SVN Ilyas',
    'SVN Indie',
    'SVN Intro Script Base Shade',
    'SVN Intro Script Base',
    'SVN Iolanthe',
    'SVN Jane Austen',
    'SVN Janelotus',
    'SVN Jealous',
    'SVN Jonesy Script',
    'SVN Jonitha Script',
    'SVN Journey',
    'SVN Just Saying',
    'SVN Just Sunday',
    'SVN Justice League',
    'SVN Karasha',
    'SVN Karlita',
    'SVN Kashima Brush',
    'SVN Kelso',
    'SVN KG Broken Vessels Sketch',
    'SVN Kingtom',
    'SVN Kitten',
    'SVN Koma',
    'SVN Konfuciuz',
    'SVN Kontras',
    'SVN Korean Calligraphy',
    'SVN La Paloma',
    'SVN Larch Shaded',
    'SVN Last Paradise',
    'SVN Le Beaune New',
    'SVN Le Murmure',
    'SVN Lemon Tuesday',
    'SVN LeOsler',
    'SVN Lifehack Basic',
    'SVN Lifehack Sans',
    'SVN Lifehack Script',
    'SVN Little Pea',
    'SVN Lolapeluza Black',
    'SVN Longstride',
    'SVN Lostar',
    'SVN Love Potion',
    'SVN Lovecure',
    'SVN Ludicrous',
    'SVN Lust Script',
    'SVN Mabella',
    'SVN Madre Script',
    'SVN Magnificent',
    'SVN Manchester Park',
    'SVN Mangoberry',
    'SVN Manus',
    'SVN Maphylla',
    'SVN Marcel Script Pro',
    'SVN Marpesia Pro',
    'SVN Marujo Fino',
    'SVN Marujo Pictures',
    'SVN Marujo',
    'SVN Maudy Script',
    'SVN Megante',
    'SVN Melissa',
    'SVN Mercuria',
    'SVN Mercury Script Bold',
    'SVN Mercury Script Light',

    'SVN Mercury Script Regular',
    'SVN Micheline',
    'SVN Modern Society',
    'SVN Momento',
    'SVN Moon Earth',
    'SVN MORVA',
    'SVN MoshiMoshi',
    'SVN Mothica',
    'SVN Mukadua',
    'SVN Naive Inline Bold',
    'SVN Nautica',
    'SVN New Athletic M54',
    'SVN Nexa Rust Handmade Extended',
    'SVN Nexa Rust Sans Black',
    'SVN Nexa Rust Script',
    'SVN Nexa Rust Slab Black Shadow',
    'SVN Nickainley Script',
    'SVN Night Wind Sent',
    'SVN Norse Bold',
    'SVN Norse Regular',
    'SVN Notera',
    'SVN Nothing',
    'SVN Notulen Serif Display ExtraBold',
    'SVN Novelia',
    'SVN Nubya',
    'SVN Nuit',
    'SVN Okami',
    'SVN One Day',
    'SVN Oriental Kaishu',
    'SVN Palaima LC',
    'SVN Palmaton',
    'SVN PalmerLakePrint',
    'SVN PalmerLakeScript',
    'SVN Paradise',
    'SVN Paris Pro',
    'SVN Passion',
    'SVN Pasternak',
    'SVN Pateglamt Script',
    'SVN Pentastic',
    'SVN Pequena Neo Black',
    'SVN Pequena Neo Regular',
    'SVN Pleasent',
    'SVN Posterizer KG Inline',
    'SVN Progs',
    'SVN Pyes Pa Headline',
    'SVN Qalisha Signature Script',
    'SVN Qalisha Signature Serif',
    'SVN Quarzo',
    'SVN Quattrocento Bold',
    'SVN Quattrocento Regular',
    'SVN Radiant Slender',
    'SVN Rawkstone',
    'SVN Redtowns',
    'SVN Reklama CF',
    'SVN Reklame Script',
    'SVN Retron 2000',
    'SVN RidemyBike Pro Bold',
    'SVN RidemyBike Pro Regular',
    'SVN Ringdena',
    'SVN Rio 2016',
    'SVN Risotto Script Pro',
    'SVN Road Rage',
    'SVN Roadbrush',
    'SVN Rockness',
    'SVN Rohtwo',
    'SVN RollgatesLuxury',
    'SVN Romaji Mincho',
    'SVN Rosalinda',
    'SVN Roselina Script',
    'SVN Rosellinda Alyamore',
    'SVN Ruca',
    'SVN Rush Hour',
    'SVN Rushtick',
    'SVN Sablon Washed Super',
    'SVN Safina Script',
    'SVN Sage 2',
    'SVN Sage',
    'SVN Saint Monica',
    'SVN Saldina',
    'SVN Salty Sans',
    'SVN Salty Script',
    'SVN Sambay',
    'SVN Santillana Daughter',
    'SVN Santis',
    'SVN Sarifa',
    'SVN Saudagar',
    'SVN Saycheez',
    'SVN Secesja Pro',
    'SVN Seiston',
    'SVN Servetica Medium',
    'SVN Servetica Thin',
    'SVN Sevillana',
    'SVN Sharpen',
    'SVN Shikamaru',
    'SVN Shintia Script',
    'SVN Showcase Sans',
    'SVN Showcase Slab',
    'SVN Sign Painter House Script',
    'SVN Signatrue',
    'SVN Silver',
    'SVN Skill',
    'SVN Slabrush',
    'SVN Slow Attack 2',
    'SVN Slow Attack',
    'SVN Smirk',
    'SVN Snell Roundhand Script Bold',
    'SVN Snell Roundhand Script',
    'SVN Space Age',
    'SVN Spencerio',
    'SVN Splandor',
    'SVN Standly',
    'SVN Steady',
    'SVN Stella',
    'SVN Stereoflows',
    'SVN Stick A Round',
    'SVN Sticky Toffee Pudding',
    'SVN Stiff Staff',
    'SVN Stingray',
    'SVN Storyteller Sans',
    'SVN Storyteller Script',
    'SVN Storyteller Serif',
    'SVN Stradas',
    'SVN Strangelove',
    'SVN Studio Brush',
    'SVN Suargie',
    'SVN Sunday',
    'SVN Sunflora',
    'SVN Sunflower',
    'SVN Sunshine',
    'SVN Supercell Magic',
    'SVN Swashington',
    'SVN Sweetie',
    'SVN Swissquote Medium',
    'SVN Swissquote Regular',
    'SVN Taken by Vultures',
    'SVN Tamarindo',
    'SVN Tangerine',
    'SVN Tanglewoods Sans',
    'SVN Tanglewoods Script',
    'SVN Teaters',
    'SVN The Carpenter Bold',
  
    'SVN The Carpenter Regular',
    'SVN The Cats Whiskers',
    'SVN The Secret',
    'SVN The Untold Story',
    'SVN The Wild Things Sans',
    'SVN The Wild Things Script',
    'SVN Tingler Script',
    'SVN Tioxo Sans',
    'SVN Tipper',
    'SVN TokigPx',
    'SVN Top Secret',
    'SVN ToySans',
    'SVN TradeMark',
    'SVN Trench',
    'SVN Truffaux Pro',
    'SVN Twilight Script',
    'SVN Uncle Ben',
    'SVN Unthrift',
    'SVN UT Triumph Press',
    'SVN UT Triumph Regular',
    'SVN Vala',
    'SVN Vampires',
    'SVN Vandella',
    'SVN Vanilla Daisy Pro',
    'SVN Velvetberries',
    'SVN Veneer',
    'SVN Verveine',
    'SVN Very Berry',
    'SVN Victoria',
    'SVN Wallington',
    'SVN Wallows',
    'SVN Water Bold',
    'SVN Water Regular',
    'SVN We Youth',
    'SVN Wednesday',
    'SVN Wellfont',
    'SVN Wendi',
    'SVN Woodpecker',
    'SVN Writing Tresno',
    'SVN Wrong Hunt',
    'SVN Wylie Voigen',
    'SVN XXII Grober Pinsel',
    'SVN XXII Yeah Script',
    'SVN Yamet Kudasi',
    'SVN Yipes',
    'SVN Young Love',
    'SVN Zailla Script',
    'SVN Zatiyan',
    'SVN Zelda Sans',
    'SVN Ziclets',
    'tahoma',
    'TH Hopeitissed',
    'UTM A&S Graceland',
    'UTM A&S Heartbeat',
    'UTM A&S Signwriter',
    'UTM Agin',
    'UTM Alpine KT',
    'UTM Aquarelle',
    'UTM Bustamalaka',
    'UTM Caviar',
    'UTM Diana',
    'UTM Dinh Tran',
    'UTM Duepuntozero',
    'UTM EdwardianB',
    'UTM EdwardianKT',
    'UTM French Vanilla',
    'UTM Gloria',
    'UTM Gradoo',
    'UTM IsadoraR',
    'UTM LinotypeZapfino KT',
    'UTM Neo Sans Intel',
    'UTM Neo Sans IntelBold',
    'UTM Neo Sans IntelBold Italic',
    'UTM Neo Sans Intel Italic',
    'UTM Novido',
    'UTM Pierre',
    'UTM Sarah',
    'UTM Scriptina KT',
    'UTM Silk Script',
    'UTM Sloop 1',
    'UTM Soraya',
    'UTM Spring',
    'UTM Swashes',
    'UTM ViceroyJF',
    'UTM Wedding K&T',
    'UTM Yen Tu',
    'UTM Yves KT',
    'UTM Yves KT Bold',
    'UTM Zirkon',
    'UVF Kizo',
    'UVF LH Line1 Sans Thin',
    'UVNBucThu',
    'UVNConThuy',
    'UVNHoaTay1',
    'UVNHuongQue R',
    'UVNKeChuyen1',
    'UVNKeChuyen2',
    'UVNKeChuyen3',
    'UVNKieu R',
    'UVNLYDO',
    'UVNMauTim1',
    'UVNMauTim2',
    'UVNMuaThu',
    'UVNSangSong R',
    'UVNThoiDai1',
    'UVNThuTu',
    'zitroneFY'
];